GROUND_Y_LEVEL = 72.0  # Example: y level where the ground is located
GRAVITY = 0.08
VERTICAL_DRAG = 0.98
TERMINAL_VELOCITY = -3.92
FRICTION = 0.6
DEBUG = True 
VELOCITY_THRESHOLD = 0.003 # difference to round velocity to 0
PLAY_PACKETS = {
        0x26: "Keep Alive",
        0x2a: "Update Light",
        0x49: "Update Section Blocks (2 or more in chunk changed)",
        0x64: "Update time (1 second)",
        0x1d: "Disconnect",
        0x6c : "System chat message",
        0x42 : "Remove Entities",
        0x3d : "Player Info Remove",
        0x0d: "Chunk batch start",
        0x0c: "Chunk batch finished",
        0x29 : "Show particle effect",
        0x1a : "Damage Event",
        0x70 : "Teleport Entity (moves more than 8 blocks)",
        0x58 : "Set Entity Metadata",
        0x5a : "Set Entity Velocity",
        0x06: "Block broken",
        0x28: "Play sound world event",
        0x74 : "Update Advancements",
        0x1f : "Entity Event / Entity Status",
        0x5d : "Set Health",
        0x5c : "Set Experience",
        0x39 : "Receive Chat Message",
        0x48: "set head rotation",
        0x30: "update entity rotation",
        0x2f: "Update Entity Position and Rotation",
        0x58: "Set Entity Metadata",
        0x2e: "Update Entity Position",
        0x75: "Update Attributes",
        0x09: "Block Update",
        0x07: "Registry Data",
        0x27: "Chunk Data and Update Light",
        0x56 : "Set Default Spawn Position",
        0x68: "Sound Effect",
        0x22 : "GAME EVENT",
        0x71 : "Set Ticking State",
        0x72 : "Step Tick",
        0x54 : "Set Center Chunk",
        0x13 : "Set Container Content",
        0x2b : "Login (play)",
        0xb : "Difficulty Info",
        0x38 : "Player Abilities (clientbound)",
        0x53 : "Set Held Item (clientbound)",
        0x77 : "Update Recipes",
        0x1f : "Entity Event",
        0x11 : "Commands",
        0x41 : "Update Recipe Book",
        0x40 : "Synchronize Player Position",
        0x4b : "Server Data (MOTD and Icon)",
        0x3e : "Player Info Update (Tab)",
        0x3e : "Player Info Update (Tab)",
        0x25: "Initialize World Border"
}
