"""Generate all packets, blocks, and other asset data extracted from Minecraft"""
import logging
import json

def generate():
    packets = None
    
    if packets is None:
        with open("./generated/generated/reports/packets.json", "r") as file:
            packets = json.load(file)
    
    pool = packets["play"]["clientbound"]
    
    with open("./packets.py", "w") as file:
        file.write("\"\"\"Generated by generate.py\"\"\"")
        file.write("from dataclasses import dataclass\n")
        file.write("\n")
        file.write("@dataclass(frozen=True)\n")
        file.write("class Clientbound:\n")
        
        for packet in pool:
            protocol_id = hex(pool[packet]["protocol_id"])
            packet = packet.split(":")[1]
            file.write(f"    {packet}: int = {protocol_id}\n")
            
        file.write("\n")
        file.write("    @classmethod\n")
        file.write("    def for_id(cls, p_id: int) -> str:\n")
        file.write("        for attr, value in cls.__dict__.items():\n")
        file.write("            if not attr.startswith('__'):  # Ignore special attributes like __module__\n")
        file.write("                if value == p_id:\n")
        file.write("                    return attr\n")
        file.write("        return \"\"\n\n")
        file.flush()
        file.close()

if __name__ == "__main__":
    import subprocess
    import argparse

    parser = argparse.ArgumentParser(description="Generate the packets.py file from generated server reports")
    parser.add_argument("-r", "--reports", help="Generate the reports from the server jar", action='store_true')

    # Parse arguments
    args = parser.parse_args()
    
    if args.reports:
        rv = subprocess.call(("cd ./generated && " +
                          "java -DbundlerMainClass='net.minecraft.data.Main' -jar " +
                          "../server/server.jar --reports"
                          ), shell=True)

    generate()

